name: Build project
inputs:
  build-type:
    description: The CMake build type (Debug, Release or RelWithDebInfo)
    type: choice
    options:
      - Debug
      - Release
      - RelWithDebInfo
    default: Release
  build-tests:
    description: If true, build unit test executables
    type: boolean
    default: false
  build-benches:
    description: If true, build benchmark executables
    type: boolean
    default: false
runs:
  using: composite
  steps:
    - name: Configure project
      run: ./scripts/configure.sh -DCMAKE_BUILD_TYPE=${{inputs.build-type}} -DKORIN_BUILD_UNITS=${{inputs.build-tests}} -DKORIN_BUILD_BENCHES=${{inputs.build-benches}}
      shell: bash
    - name: Build project
      run: |
        pushd ./build
        make
        popd
      shell: bash